const express=require('express')
const app=express()
const {createtodo}=require("../controller/createtodo")
const router=express.Router()
router.post("/createtodo",createtodo)
const {gettodo}=require("../controller/gettodo")
router.get("/gettodo",gettodo)
const {gettodobyId}=require("../controller/gettodo")
router.get("/gettodos/:id",gettodobyId)
const {deletetodo}=require("../controller/deletetodo")
router.delete("/deletetodo/:id",deletetodo)
const {updatetodo}=require("../controller/updatetodo")
router.put("/updatetodo/:id",updatetodo)
module.exports=router
